"""Fix GameResult and Prize relationships

Revision ID: 6b5658b0ab18
Revises: 
Create Date: 2023-09-01 19:42:27.630932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b5658b0ab18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prize',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('significant_other_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['significant_other_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('click',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_session_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=False),
    sa.Column('satisfied', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prize_selection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_result_id', sa.Integer(), nullable=False),
    sa.Column('prize_id', sa.Integer(), nullable=False),
    sa.Column('satisfied', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_result_id'], ['game_result.id'], ),
    sa.ForeignKeyConstraint(['prize_id'], ['prize.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prize_selection')
    op.drop_table('game_result')
    op.drop_table('click')
    op.drop_table('user')
    op.drop_table('prize')
    op.drop_table('game_session')
    # ### end Alembic commands ###
